apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: incubyte-assignment
  labels:
    app: flask
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
